model:
  openai: 'gpt-4o'
  anthropic: 'claude-3-7-sonnet-latest'
  google: 'gemini-2.5-pro-exp-03-25'

queries:
  local: "Reston, Virginia news"
  # regional: "Northern Virginia news"
  # national: "United States news"
  # global: "Latest global news"

